### ISSUE TITLE
XAD_ERROR_NTAPI

### ISSUE THREAD

**Issue by ghost** [strivexjun/XAntiDebug#6]
Why this error?
 
Source codes in repo https://github.com/lurumdare/khaleesi/tree/xantidebug
commit https://github.com/lurumdare/khaleesi/commit/1929297589062700abc42a51ef8eb14628282aba

**Comment by strivexjun** [comment]
in the path: \khaleesi-xantidebug\khaleesi\Shared\wow64ext.cpp .
Line: 336:   

ntdll64 = GetModuleHandle64((wchar_t*)("ntdll.dll"));
modify
ntdll64 = GetModuleHandle64((wchar_t*)(L"ntdll.dll"));

**Comment by lurumdare** [comment]
@strivexjun crash app. https://i.imgur.com/FrrQjYt.png

**Comment by ghost** [comment]
@strivexjun thanks, works.
